language: python
cache: pip

sudo: false

python:
  - "3.6"

env:
  - DJANGO=2.2

matrix:
  fast_finish: true
  include:
    - { python: "3.6", env: TOXENV=isort }
    - { python: "3.6", env: TOXENV=docs }

install:
  - pip install tox-travis

script:
  - tox

after_success:
  - pip install codecov
  - codecov -e TOXENV,DJANGO

notifications:
  email: false
