name: ci-build

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches:
      - master
      - stable/1.0.x
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

env:
  PGUSER: postgres
  PGPASSWORD: ''

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: ["isort", "docs", "py36-django22"]

    services:
      postgres:
        image: postgres:10
        env:
          POSTGRES_HOST_AUTH_METHOD: trust

        ports:
          - 5432:5432

    name: Tests (env ${{ matrix.env }})

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions

      - name: Run tox
        env:
          DJANGO: 2.2
          TOXENV: ${{ matrix.env }}
        run: tox

      - name: Publish coverage report
        env:
          DJANGO: 2.2
        uses: codecov/codecov-action@v1
